# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59ee1fb66e18ce3209b11c2ddd3e1c8e9bd06c21aff55f1258eabec000e2eb815c5227dfb44b7e3d4b51cb14a4f4b9f0fa760ac2d2a0659533b69ae64e59f936

test:
  secret_key_base: 4451dca30450f01c41d061d85f0f158298fac66d3b960d0fa706ab6403480d653f90edc1f909be9fc951c42a03cef1987fd059c071e04af73918fae55e592864

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
